### ISSUE TITLE
[BUG] angular - MicroSentryService

### ISSUE THREAD

**Issue by sup3rcow** [taiga-family/micro-sentry#67]
# 🐞 Bug report

Hi.
I'm using angular 19, and micro-sentry is provided like this:
```
provideMicroSentry({
            release: environment.version,
            dsn: environment.sentryDSN,
          }),
```

And in my code, when I want to inject MicroSentryService like this:

```
import { MicroSentryService } from '@micro-sentry/angular';

constructor(private microSentryService: MicroSentryService) {
...
}
```
I got error:
_ERROR NullInjectorError: R3InjectorError(Environment Injector)[_AuthService -> _MicroSentryService -> InjectionToken Micro Sentry Options -> InjectionToken Micro Sentry Options]: 
  NullInjectorError: No provider for InjectionToken Micro Sentry Options!_

Am I missing something? Or this is a bug?

### Versions
"@micro-sentry/angular": "7.1.1",

Angular: "@angular/core": "^19.0.1",

**Comment by sup3rcow** [comment]
I was looking in your sourcecode an mange to solve it, by installing
"@micro-sentry/browser": "7.1.1",

and adding this in ApplicationConfig providers list:
    {
      provide: MICRO_SENTRY_CONFIG,
      useValue: new InjectionToken<BrowserSentryClientOptions>('Micro Sentry Options'),
    },

**Comment by sevaru** [comment]
Hi!

You don’t need to manually install @micro-sentry/browser because it is already a dependency of @micro-sentry/angular. When you install @micro-sentry/angular, it will automatically bring in @micro-sentry/browser for you.

Additionally, you don’t need to manually provide any providers. The provideMicrosentry function in @micro-sentry/angular takes care of setting up all the necessary providers for you.

For a working example, you can check out this [stackblitz: angular 19 + micro-sentry](https://stackblitz.com/edit/micro-sentry-angular-19?file=src%2Fmain.ts) to see how to set up @micro-sentry/angular.
